kind: pipeline
name: demo

steps:
  - name: build
    image: golang:1.12
    commands:
      - pwd
      - go version
      - go build .
      - go test demo/util

  #  - name: frontend
  #    image: node:6
  #    commands:
  #      - npm install
  #      - npm test

  - name: publish
    image: plugins/docker:latest
    settings:
      username: shanli2012
      password: Shanli2016
      repo: shanli2012/dronedemo
      tags: latest

  - name: deploy
    image: appleboy/drone-ssh
    pull: true
    settings:
      host: 61.171.217.191
      username: dev
      password: 1234
      port: 22
      script:
        - cd /data/
        - mkdir app/
        - cd /data/app
        - docker rmi -f shanli2012/dronedemo
        - echo "login docker"
        - docker login --username shanli2012 --password Shanli2016
        - echo "login success, pulling..."
        - docker pull shanli2012/dronedemo:latest
        - echo "image running"
        - docker run -p 8088:8088 -d shanli2012/dronedemo
        - echo "run success"
