kind: pipeline
name: demo

steps:
  - name: build
    image: golang:1.12
    commands:
      - pwd
      - go version
      - go build .
      - go test demo/util

  #  - name: frontend
  #    image: node:6
  #    commands:
  #      - npm install
  #      - npm test
